Profiles:
  delphiGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
      - orderContainerName.delphi.com:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Organizations:
      - Name: OrdererMSPName
        ID: OrdererMSP
        MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/ordererOrganizations/delphi.com/msp
    Consortiums:
      SampleConsortium:
        Organizations:
        - Name: BUMSPName
          ID: BUMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/bu.delphi.com/msp
          AnchorPeers:
          - Host: BUContainerName.delphi.com
            Port: 7051
        - Name: ENGMSPName
          ID: ENGMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/eng.delphi.com/msp
          AnchorPeers:
          - Host: ENGContainerName.delphi.com
            Port: 7051
        - Name: PMMSPName
          ID: PMMSP
          MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/pm.delphi.com/msp
          AnchorPeers:
          - Host: PMContainerName.delphi.com
            Port: 7051
  delphiChannel:
    Consortium: SampleConsortium
    Application:
      Organizations:
      - Name: BUMSPName
        ID: BUMSP
        MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/bu.delphi.com/msp
        AnchorPeers:
        - Host: BUContainerName.delphi.com
          Port: 7051
      - Name: ENGMSPName
        ID: ENGMSP
        MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/eng.delphi.com/msp
        AnchorPeers:
        - Host: ENGContainerName.delphi.com
          Port: 7051
      - Name: PMMSPName
        ID: PMMSP
        MSPDir: /home/david/Documents/delphi-fabric/config/crypto-config/peerOrganizations/pm.delphi.com/msp
        AnchorPeers:
        - Host: PMContainerName.delphi.com
          Port: 7051