version: "3"
volumes:
  MSPROOT:
    external: true
  CONFIGTX_DIR:
    external: true
networks:
  default:
    external:
      name: delphiNetwork
services:
  ccenv:
    image: hyperledger/fabric-ccenv:x86_64-1.1.0-preview
    container_name: ccenv.Delphi.com
  OrdererServiceName.Delphi.com:
    container_name: orderContainerName
    image: hyperledger/fabric-orderer:x86_64-1.1.0-preview
    command: orderer
    ports:
    - 7250:7050
    volumes:
    - CONFIGTX_DIR:/etc/hyperledger/configtx
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/ca.crt]
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/delphi.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/msp
    - GODEBUG=netdns=go
  peer0.BU.Delphi.com:
    container_name: BUContainerName
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=BUContainerName:7051
    - CORE_PEER_LOCALMSPID=BUMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer0.BU.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer0.BU.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer0.BU.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer0.BU.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.BU.Delphi.com
    - CORE_PEER_ADDRESS=peer0.BU.Delphi.com:7051
    - GODEBUG=netdns=go
    ports:
    - 7051:7051
    - 7053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer1.BU.Delphi.com:
    container_name: BUContainer1
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=BUContainer1:7051
    - CORE_PEER_LOCALMSPID=BUMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer1.BU.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer1.BU.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer1.BU.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/BU.Delphi.com/peers/peer1.BU.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer1.BU.Delphi.com
    - CORE_PEER_ADDRESS=peer1.BU.Delphi.com:7051
    - GODEBUG=netdns=go
    ports:
    - 7061:7051
    - 7063:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer0.ENG.Delphi.com:
    container_name: ENGContainerName
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ENGContainerName:7051
    - CORE_PEER_LOCALMSPID=ENGMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/ENG.Delphi.com/peers/peer0.ENG.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/ENG.Delphi.com/peers/peer0.ENG.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/ENG.Delphi.com/peers/peer0.ENG.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/ENG.Delphi.com/peers/peer0.ENG.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.ENG.Delphi.com
    - CORE_PEER_ADDRESS=peer0.ENG.Delphi.com:7051
    - GODEBUG=netdns=go
    ports:
    - 8051:7051
    - 8053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer0.PM.Delphi.com:
    container_name: PMContainerName
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=PMContainerName:7051
    - CORE_PEER_LOCALMSPID=PMMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/PM.Delphi.com/peers/peer0.PM.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/PM.Delphi.com/peers/peer0.PM.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/PM.Delphi.com/peers/peer0.PM.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/PM.Delphi.com/peers/peer0.PM.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.PM.Delphi.com
    - CORE_PEER_ADDRESS=peer0.PM.Delphi.com:7051
    - GODEBUG=netdns=go
    ports:
    - 9051:7051
    - 9053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default