version: "3"
volumes:
  MSPROOT:
    external: true
  CONFIGTX_DIR:
    external: true
networks:
  default:
    external:
      name: delphiNetwork
services:
  ccenv:
    image: hyperledger/fabric-ccenv:x86_64-1.0.1
    container_name: ccenv.Delphi.com
  OrdererServiceName.Delphi.com:
    container_name: orderContainerName.Delphi.com
    image: hyperledger/fabric-orderer:x86_64-1.0.1
    command: orderer
    ports:
    - 7250:7050
    environment:
    - ORDERER_GENERAL_LOGLEVEL=debug
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/server.crt
    - ORDERER_GENERAL_GENESISMETHOD=file
    - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/delphi.block
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/msp
    - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto-config/ordererOrganizations/Delphi.com/orderers/orderContainerName.Delphi.com/tls/ca.crt]
    volumes:
    - CONFIGTX_DIR:/etc/hyperledger/configtx
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer0.bu.Delphi.com:
    container_name: BUContainerName.Delphi.com
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.0.1
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=BUContainerName.Delphi.com:7051
    - CORE_PEER_LOCALMSPID=BUMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/users/Admin@bu.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer0.bu.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer0.bu.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer0.bu.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.bu.Delphi.com
    - CORE_PEER_ADDRESS=peer0.bu.Delphi.com:7051
    ports:
    - 7051:7051
    - 7053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer1.bu.Delphi.com:
    container_name: BUContainer1.Delphi.com
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.0.1
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=BUContainer1.Delphi.com:7051
    - CORE_PEER_LOCALMSPID=BUMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/users/Admin@bu.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer1.bu.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer1.bu.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/bu.Delphi.com/peers/peer1.bu.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer1.bu.Delphi.com
    - CORE_PEER_ADDRESS=peer1.bu.Delphi.com:7051
    ports:
    - 7061:7051
    - 7063:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer0.eng.Delphi.com:
    container_name: ENGContainerName.Delphi.com
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.0.1
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=ENGContainerName.Delphi.com:7051
    - CORE_PEER_LOCALMSPID=ENGMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/eng.Delphi.com/users/Admin@eng.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/eng.Delphi.com/peers/peer0.eng.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/eng.Delphi.com/peers/peer0.eng.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/eng.Delphi.com/peers/peer0.eng.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.eng.Delphi.com
    - CORE_PEER_ADDRESS=peer0.eng.Delphi.com:7051
    ports:
    - 8051:7051
    - 8053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default
  peer0.pm.Delphi.com:
    container_name: PMContainerName.Delphi.com
    depends_on:
    - OrdererServiceName.Delphi.com
    image: hyperledger/fabric-peer:x86_64-1.0.1
    command: peer node start
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=PMContainerName.Delphi.com:7051
    - CORE_PEER_LOCALMSPID=PMMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/pm.Delphi.com/users/Admin@pm.Delphi.com/msp
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto-config/peerOrganizations/pm.Delphi.com/peers/peer0.pm.Delphi.com/tls/server.key
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/pm.Delphi.com/peers/peer0.pm.Delphi.com/tls/server.crt
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto-config/peerOrganizations/pm.Delphi.com/peers/peer0.pm.Delphi.com/tls/ca.crt
    - CORE_PEER_ID=peer0.pm.Delphi.com
    - CORE_PEER_ADDRESS=peer0.pm.Delphi.com:7051
    ports:
    - 9051:7051
    - 9053:7053
    volumes:
    - /run/docker.sock:/host/var/run/docker.sock
    - MSPROOT:/etc/hyperledger/crypto-config
    networks:
    - default