version: '3'
volumes:
  MSPROOT_local:
    external: true
  CONFIGTX_local:
    external: true
networks:
  default:
    external:
      name: TeekingNetwork
services:
  peer0.SUPPLY.Teeking.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=TeekingNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.SUPPLY.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=SUPPLYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/SUPPLY.Teeking.com/peers/peer0.SUPPLY.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.SUPPLY.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.SUPPLY.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '7051:7051'
      - '7053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    container_name: SupplyChain
    networks:
      - default
  peer0.CAR.Teeking.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=TeekingNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CAR.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=CARMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/CAR.Teeking.com/peers/peer0.CAR.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.CAR.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.CAR.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '8051:7051'
      - '8053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    container_name: Car
    networks:
      - default
  peer0.FACTORY.Teeking.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=TeekingNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.FACTORY.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=FACTORYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/FACTORY.Teeking.com/peers/peer0.FACTORY.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.FACTORY.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.FACTORY.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '9051:7051'
      - '9053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    container_name: Factory
    networks:
      - default
  peer0.TK.Teeking.com:
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=TeekingNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.TK.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=TkMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/TK.Teeking.com/peers/peer0.TK.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.TK.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.TK.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '6051:7051'
      - '6053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    container_name: Tk
    networks:
      - default
  orderer0:
    image: 'hyperledger/fabric-orderer:x86_64-1.1.0'
    command: orderer
    ports:
      - '7050:7050'
    volumes:
      - 'CONFIGTX_local:/etc/hyperledger/configtx'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/tk.block
      - ORDERER_GENERAL_LOCALMSPID=TkConsensusMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/TKConsensus.Teeking.com/orderers/orderer0.TKConsensus.Teeking.com/msp
      - GODEBUG=netdns=go
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    networks:
      default:
        aliases:
          - orderer0
    container_name: orderer0
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
  orderer1:
    image: 'hyperledger/fabric-orderer:x86_64-1.1.0'
    command: orderer
    ports:
      - '8050:7050'
    volumes:
      - 'CONFIGTX_local:/etc/hyperledger/configtx'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/tk.block
      - ORDERER_GENERAL_LOCALMSPID=TkConsensusMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/TKConsensus.Teeking.com/orderers/orderer1.TKConsensus.Teeking.com/msp
      - GODEBUG=netdns=go
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    networks:
      default:
        aliases:
          - orderer1
    container_name: orderer1
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
  orderer2:
    image: 'hyperledger/fabric-orderer:x86_64-1.1.0'
    command: orderer
    ports:
      - '9050:7050'
    volumes:
      - 'CONFIGTX_local:/etc/hyperledger/configtx'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/tk.block
      - ORDERER_GENERAL_LOCALMSPID=TkConsensusMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/TKConsensus.Teeking.com/orderers/orderer2.TKConsensus.Teeking.com/msp
      - GODEBUG=netdns=go
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    networks:
      default:
        aliases:
          - orderer2
    container_name: orderer2
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
  zookeeper0:
    image: 'hyperledger/fabric-zookeeper:x86_64-0.4.6'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ZOO_MY_ID=0
      - 'ZOO_SERVERS=server.0=zookeeper0:2888:3888 server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 '
    networks:
      default:
        aliases:
          - zookeeper0
    container_name: zookeeper0
  zookeeper1:
    image: 'hyperledger/fabric-zookeeper:x86_64-0.4.6'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ZOO_MY_ID=1
      - 'ZOO_SERVERS=server.0=zookeeper0:2888:3888 server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 '
    networks:
      default:
        aliases:
          - zookeeper1
    container_name: zookeeper1
  zookeeper2:
    image: 'hyperledger/fabric-zookeeper:x86_64-0.4.6'
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      - ZOO_MY_ID=2
      - 'ZOO_SERVERS=server.0=zookeeper0:2888:3888 server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 '
    networks:
      default:
        aliases:
          - zookeeper2
    container_name: zookeeper2
  kafka0:
    image: 'hyperledger/fabric-kafka:x86_64-0.4.6'
    environment:
      - KAFKA_BROKER_ID=0
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181'
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      default:
        aliases:
          - kafka0
    container_name: kafka0
  kafka1:
    image: 'hyperledger/fabric-kafka:x86_64-0.4.6'
    environment:
      - KAFKA_BROKER_ID=1
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181'
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      default:
        aliases:
          - kafka1
    container_name: kafka1
  kafka2:
    image: 'hyperledger/fabric-kafka:x86_64-0.4.6'
    environment:
      - KAFKA_BROKER_ID=2
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181'
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      default:
        aliases:
          - kafka2
    container_name: kafka2
  kafka3:
    image: 'hyperledger/fabric-kafka:x86_64-0.4.6'
    environment:
      - KAFKA_BROKER_ID=3
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181'
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
    ports:
      - 9092
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    networks:
      default:
        aliases:
          - kafka3
    container_name: kafka3
