version: '3'
volumes:
  MSPROOT_local:
    external: true
  CONFIGTX_local:
    external: true
networks:
  default:
    external:
      name: delphiNetwork
services:
  peer0.SUPPLY.Teeking.com:
    depends_on:
      - orderContainerName
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.SUPPLY.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=SUPPLYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/SUPPLY.Teeking.com/peers/peer0.SUPPLY.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.SUPPLY.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.SUPPLY.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '7051:7051'
      - '7053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    container_name: SupplyChain
    networks:
      - default
  ca.SUPPLY.Teeking.com:
    image: 'hyperledger/fabric-ca:x86_64-1.1.0'
    command: sh -c 'fabric-ca-server start -d'
    volumes:
      - 'MSPROOT_local:/etc/hyperledger/fabric-ca-server'
    ports:
      - '7054:7054'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server/peerOrganizations/SUPPLY.Teeking.com/ca
      - GODEBUG=netdns=go
    container_name: ca.SUPPLY.Teeking.com
    networks:
      - default
  peer0.CAR.Teeking.com:
    depends_on:
      - orderContainerName
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.CAR.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=CARMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/CAR.Teeking.com/peers/peer0.CAR.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.CAR.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.CAR.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '8051:7051'
      - '8053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    container_name: Car
    networks:
      - default
  peer0.FACTORY.Teeking.com:
    depends_on:
      - orderContainerName
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.FACTORY.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=FACTORYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/FACTORY.Teeking.com/peers/peer0.FACTORY.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.FACTORY.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.FACTORY.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '9051:7051'
      - '9053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    container_name: Factory
    networks:
      - default
  peer0.TK.Teeking.com:
    depends_on:
      - orderContainerName
    image: 'hyperledger/fabric-peer:x86_64-1.1.0'
    command: peer node start
    environment:
      - 'CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock'
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=delphiNetwork
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LEDGER_HISTORY_ENABLEHISTORYDATABASE=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - 'CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.TK.Teeking.com:7051'
      - CORE_PEER_LOCALMSPID=TkMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto-config/peerOrganizations/TK.Teeking.com/peers/peer0.TK.Teeking.com/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ID=peer0.TK.Teeking.com
      - 'CORE_PEER_ADDRESS=peer0.TK.Teeking.com:7051'
      - CORE_CHAINCODE_EXECUTETIMEOUT=180s
      - GODEBUG=netdns=go
    ports:
      - '6051:7051'
      - '6053:7053'
    volumes:
      - '/run/docker.sock:/host/var/run/docker.sock'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    container_name: Tk
    networks:
      - default
  orderContainerName:
    image: 'hyperledger/fabric-orderer:x86_64-1.1.0'
    command: orderer
    ports:
      - '7050:7050'
    volumes:
      - 'CONFIGTX_local:/etc/hyperledger/configtx'
      - 'MSPROOT_local:/etc/hyperledger/crypto-config'
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/tk.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto-config/ordererOrganizations/Teeking.com/orderers/orderContainerName.Teeking.com/msp
      - GODEBUG=netdns=go
    networks:
      default:
        aliases:
          - orderContainerName
    container_name: orderContainerName
